#BLUE SET=======================================================================================                                                                                                      
#COLORS = ['#ece7f2', '#a6bddb', '#2b8cbe'] #for GROUP_SIZE = 3                                                                                                                                      
#COLORS = ['#f1eef6', '#bdc9e1', '#74a9cf', '#0570b0'] #for GROUP_SIZE = 4                                                                                                                            
#COLORS = ['#f1eef6', '#bdc9e1', '#74a9cf', '#2b8cbe', '#045a8d'] #for GROUP_SIZE = 5                                                                                                                
#COLORS = ['#f1eef6', '#d0d1e6', '#a6bddb', '#74a9cf', '#2b8cbe', '#045a8d'] #for GROUP_SIZE = 6                                                                                                      
#COLORS = ['#f1eef6', '#d0d1e6', '#a6bddb', '#74a9cf', '#3690c0', '#0570b0', '#034e7b'] #for GROUP_SIZE = 7                                                                                          
#COLORS = ['#fff7fb', '#ece7f2', '#d0d1e6', '#a6bddb', '#74a9cf', '#3690c0', '#0570b0', '#034e7b'] #for GROUP_SIZE = 8                                                                                
#COLORS = ['#fff7fb', '#ece7f2', '#d0d1e6', '#a6bddb', '#74a9cf', '#3690c0', '#0570b0', '#045a8d', '#023858'] #for GROUP_SIZE = 9                                                                    
                                                                                                                                                                                                     
#RED SET========================================================================================                                                                                                      
#COLORS = ['#fee8c8', '#fdbb84', '#e34a33'] #for GROUP_SIZE = 3                                                                                                                                      
COLORS = ['#fdcc8a', '#fc8d59', '#d7301f'] #for GROUP_SIZE = 3(2)                                                                                                                                    
#COLORS = ['#fef0d9', '#fdcc8a', '#fc8d59', '#d7301f'] #for GROUP_SIZE = 4                                                                                                                            
#COLORS = ['#fef0d9', '#fdcc8a', '#fc8d59', '#e34a33', '#b30000'] #for GROUP_SIZE = 5                                                                                                                
#COLORS = ['#fef0d9', '#fdd49e', '#fdbb84', '#fc8d59', '#e34a33', '#b30000'] #for GROUP_SIZE = 6                                                                                                      
#COLORS = ['#fef0d9', '#fdd49e', '#fdbb84', '#fc8d59', '#ef6548', '#d7301f', '#990000'] #for GROUP_SIZE = 7                                                                                          
#COLORS = ['#fff7ec', '#fee8c8', '#fdd49e', '#fdbb84', '#fc8d59', '#ef6548', '#d7301f', '#990000'] #for GROUP_SIZE = 8                                                                                
#COLORS = ['#fff7ec', '#fee8c8', '#fdd49e', '#fdbb84', '#fc8d59', '#ef6548', '#d7301f', '#b30000', '#7f0000'] #for GROUP_SIZE = 9